---
ops: [evaluate]
model: {
    path: /home/sb14489/Epigenomics/ML_ACR/Selene_AllModels_BashRun_ymlFiles/DanQ_model.py,
    class: DanQ,
    class_args: {
        sequence_length: 1000,
        n_targets:  ,
    },
    non_strand_specific: mean
}



sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path:
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path:
    },
    target_path:  ,
    intervals_path: /scratch/sb14489/0.Reference/Maize_B73/zm_genome_interval.bed,
    test_holdout: [chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9],
    seed: 127,
    mode: train,
    save_datasets: [train],
    output_dir: ,
    sample_negative: False,
    sequence_length: 1000,
    center_bin_to_predict: 500,
    feature_thresholds: 0.5

}

evaluate_model: !obj:selene_sdk.EvaluateModel {
    batch_size: 64,
    n_test_samples: 10000,
    features:  !obj:selene_sdk.utils.load_features_list {
        input_path:
    },
    use_cuda: False,
    report_gt_feature_n_positives: 50,
    trained_model_path:  ,
    output_dir:
}
random_seed: 123
...
