---
ops: [evaluate]
model: {
    path: /home/sb14489/ACR_ML_caQTLs/Deep_Former/Selene_Ex/deeperdeepsea.py,
    class: DeeperDeepSEA,
    class_args: {
        sequence_length: 1000,
        n_targets: 33,
    },
    non_strand_specific: mean
}



sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /scratch/sb14489/0.Reference/Maize_B73/Zm-B73-REFERENCE-NAM-5.0_OnlyChr.fa
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /scratch/sb14489/8.ML_ACR/1.InputBed/Seedling_distinct_features.txt
    },
    target_path: /scratch/sb14489/8.ML_ACR/1.InputBed/sorted_Seedling_Peaks.bed.gz,
    intervals_path: /scratch/sb14489/0.Reference/Maize_B73/zm_genome_interval.bed,
    test_holdout: [chr8],
    seed: 127,
    sample_negative: False,
    sequence_length: 1000,
    center_bin_to_predict: 500,
    feature_thresholds: 0.5

}

evaluate_model: !obj:selene_sdk.EvaluateModel {
    batch_size: 64,
    n_test_samples: 455024,
    features:  !obj:selene_sdk.utils.load_features_list {
        input_path: /scratch/sb14489/8.ML_ACR/1.InputBed/Seedling_distinct_features.txt
    },
    use_cuda: False,
    report_gt_feature_n_positives: 50,
    trained_model_path: /scratch/sb14489/8.ML_ACR/2.DeeperDeepSea_Test/500bp_AllGenome/best_model.pth.tar,
    output_dir: ./500bp_AllGenome_Evaluation
}
random_seed: 123
...
