---
ops: [evaluate]
model: {
    path: /home/sb14489/ACR_ML_caQTLs/Deep_Former/DanQ_model.py,
    class: DanQ,
    class_args: {
        sequence_length: 1000,
        n_targets: 19,
    },
    non_strand_specific: mean
}

sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        # we include relative paths here, but we recommend using absolute
        # paths for future configuration files
        input_path: /scratch/sb14489/8.ML_ACR/DeepFormer_Ex/DeepFormer/data/Zea_mays.B73_RefGen_v4.dna.toplevel.fa
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /scratch/sb14489/8.ML_ACR/DeepFormer_Ex/DeepFormer/data/distinct_features.txt
    },
    target_path: /scratch/sb14489/8.ML_ACR/DeepFormer_Ex/DeepFormer/data/sorted_zm.bed.gz,
    intervals_path: /scratch/sb14489/8.ML_ACR/DeepFormer_Ex/DeepFormer/data/zm_genome_interval.bed,
    seed: 127,
    # A positive example is an 1000bp sequence with at least 1 class/feature annotated to it.
    # A negative sample has no classes/features annotated to the sequence.
    sample_negative: True,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    test_holdout: [chr02], ## Want to use only Test but Validation seems like default
    validation_holdout: [chr05],
    # The feature must take up 50% of the bin (200bp) for it to be considered
    # a feature annotated to that sequence.
    feature_thresholds: 0.5
}


evaluate_model: !obj:selene_sdk.EvaluateModel {
    batch_size: 64,
    n_test_samples: 1000,
    features:  !obj:selene_sdk.utils.load_features_list {
        input_path: /scratch/sb14489/8.ML_ACR/DeepFormer_Ex/DeepFormer/data/distinct_features.txt
    },
    use_cuda: True,
    report_gt_feature_n_positives: 50,
    trained_model_path: /scratch/sb14489/8.ML_ACR/DeepFormer_Ex/DeepFormer/maize_code/DanQ/best_model.pth.tar,
    output_dir: DanQ_ExData/evaluation_outputs
}
random_seed: 123
...
