---
title: "Getting FC (Bif3/WT) of gene body chromatin acc"
author: "Sohyun Bang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document
---
```{r setopts, echo=FALSE}
library(edgeR)
library(preprocessCore)
library(dplyr)
library(tidyr)
library(ggVennDiagram)

rm(list = ls())
## Save figures as pdf files for illustrator. Save figures as png files for md visualization. 
knitr::opts_chunk$set(
  echo = TRUE,
  dev = c("png", "pdf"),
  fig.keep = "all"
)
options(getClass.msg = FALSE)

set_fig_path <- function(options) {
  options$fig.path <- "output/fig-"
  options
}
knitr::opts_hooks$set(dev = set_fig_path)
```
### Load Gene Info data
```{r Load gene Info data}
GeneInfo <- read.delim("../maizev5_data/Zm00001eb.1.fulldata_Curated2.txt", stringsAsFactors = FALSE)
```


### 1) Get Gene body acc for all the genes & normalize the value & calculate logFC
```{r Load Data - GeneBodyACC for all cell types}
### 1) Get Gene body acc for all the genes
## load gene*cell table.
WT_GeneXCT <- read.table("./A619_AnnV4.GeneBodyACC.byGeneXCT.txt",header=TRUE)
Bif3_GeneXCT <- read.table("./Bif3_AnnV4.GeneBodyACC.byGeneXCT.txt",header=TRUE)
Celltypes <- colnames(WT_GeneXCT)[-1]
colnames(Bif3_GeneXCT)[-1] <- paste("Bif3&", colnames(Bif3_GeneXCT)[-1], sep="")
colnames(WT_GeneXCT)[-1] <- paste("A619&", colnames(WT_GeneXCT)[-1], sep="")

GeneXCT <- merge(WT_GeneXCT, Bif3_GeneXCT, by = "gene")
head(GeneXCT)

## normalization
GeneNames <- GeneXCT[, 1]
gene_counts_df <- GeneXCT[, -1]

## Set up the cut off to 50!
#head(GeneXCT)
#dim(GeneXCT)

GeneXCT_MoreThan50Tn5 <- GeneXCT %>%
  filter_all(all_vars(. > 50))
dim(GeneXCT_MoreThan50Tn5)

GeneNames <- GeneXCT[, 1]
gene_counts_df <- GeneXCT[, -1]

cpm_data <- cpm(DGEList(counts = gene_counts_df), log = FALSE)
QNorm <- normalize.quantiles(as.matrix(gene_counts_df))
rownames(QNorm) <- GeneNames
colnames(QNorm) <- colnames(GeneXCT[,-1])
#head(QNorm)
#dim(QNorm)

# Build fold change table
FCTable <- as.data.frame(sapply(Celltypes, function(Celltypes) {
  bif3_col <- paste0("Bif3&", Celltypes)
  A619_col <- paste0("A619&", Celltypes)
  log2(QNorm[, bif3_col] / QNorm[, A619_col])
}))

#Matching with gene names
FCTable_with_id <- FCTable %>%
  tibble::rownames_to_column(var = "gene_model")

FCTable_annotated <- FCTable_with_id %>%
  left_join(GeneInfo[, c("gene_model", "locus_symbol")], by = "gene_model")
write.table(FCTable_annotated, file = "GeneBodyACC_FC_Bif3WT_byCelltypes.txt", sep = "\t", row.names = FALSE, quote = FALSE)

CentralZone_Increased <- FCTable_annotated %>%
  filter(IM.OC > 0.5)

```
### 2) Load Homemodomain TFs and match from V3 to V5
```{r check the types of TFs}
TFlist <- read.delim("./Zma_TF_list.txt", stringsAsFactors = FALSE) ## This data is from https://planttfdb.gao-lab.org/index.php?sp=Zma

## Filter TFs with HD
Temp <- TFlist %>%
  filter(Family %in% c("ZF-HD", "HD-ZIP", "WOX", "HB0PHD", "HB-other"))

V3_V5 <- read.delim("B73v3_to_B73v5.tsv", stringsAsFactors = FALSE)

TFs_merged <- merge(TFlist, V3_V5, by.x = "Gene_ID", by.y = "V3", all.x = TRUE)
TFs_expanded <- TFs_merged %>% ## This is because to make V5 gene id as the key
  separate_rows(V5, sep = ",") %>%
  rename(gene_model=V5) 

TFs_V5Key <- TFs_expanded %>%
  group_by(gene_model) %>%
  summarise(Family = paste(sort(unique(Family)), collapse = ","), .groups = "drop") %>%
  filter(gene_model != "") %>%
  separate_rows(Family, sep = ",") # This is because some gene model has two families

HD_TFs <- TFs_V5Key %>%
    filter(Family %in% c("ZF-HD", "HD-ZIP", "WOX", "HB0PHD", "HB-other")) 

unique_HD_TFs<- unique(HD_TFs$gene_model)
length(unique_HD_TFs)

```

### 3) Load De novo marker gene list
```{r check De novo marker gene list}
DeNovo <- read.delim("A619_v4.IM.OC_deseq_2_results.tsv", stringsAsFactors = FALSE)
Sig_DeNovo <- DeNovo[!is.na(DeNovo$padj) & 
                     !is.na(DeNovo$log2FoldChange) & 
                     DeNovo$pvalue < 0.01 & 
                     DeNovo$log2FoldChange > 0, ]

Sig_DeNovo_annotated <- Sig_DeNovo %>%
  rename(gene_model = gene_name) %>%
  left_join(GeneInfo[, c("gene_model", "locus_symbol")], by = "gene_model")
write.table(Sig_DeNovo_annotated, file = "Sig_DeNovo_p0.01_genesymbol.txt", sep = "\t", row.names = FALSE, quote = FALSE)

```


### 4) Venn diagram
```{r Venn diagram , fig.width=3, fig.height=3}
common_elements <- intersect(intersect(unique_HD_TFs, CentralZone_Increased$gene_model), Sig_DeNovo_annotated$gene_model)
print(common_elements)
venn_list <- list(HD_TF = unique_HD_TFs, 
                  IncreasedinBif3 = CentralZone_Increased$gene_model,
                  DeNovoCentralzone = Sig_DeNovo_annotated$gene_model)
ggVennDiagram(venn_list, label="count")

```